version: "3.1"

services: 
    nginx-server:
        image: nginx:latest
        container_name: websy-nginx-server
        restart: always
        volumes:
            - /home/developer:/home
            - /home/developer/docker/websy_lamp/nginx/conf:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm
            - mariadb
            - mongodb
    php-fpm:
        #image: php:5.6-fpm
        image: php:fpm
        container_name: websy-php-fpm
        restart: always
        build:
            context: .
            dockerfile: php-fpm/Dockerfile
        volumes:
            - /home/developer:/home
            - /home/developer/docker/websy_lamp/php-fpm/php.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        links:
            - mariadb
            - mongodb
    mariadb:
        image: mariadb:latest
        container_name: websy-mariadb
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - /home/developer/docker/websy_lamp/mariadb/conf:/etc/mysql/conf.d
        environment:
          - MYSQL_ROOT_PASSWORD=root       
          - MYSQL_USER=root      
          - MYSQL_PASSWORD=root      
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: websy-phpmyadmin
        restart: always
        ports:
            - "8080:80"
        links:
            - mariadb:db  
    mongodb:
        image: mongo:3
        command: mongod --noprealloc --smallfiles --replSet mongodb --dbpath /data/db --nojournal --oplogSize 16 --noauth
        container_name: websy-mongodb
        restart: always
        volumes:
            - /home/developer/docker/websy_lamp/mongodb/data:/data/db
        ports:
            - "27017:27017"  
        links:
            - nodejs    
    nodejs:
        image: node:6
        container_name: websy-nodejs
        restart: always
        build:
            context: .
            dockerfile: nodejs/Dockerfile
        ports:
            - "8009:8009"  
        volumes:
            - /home/developer:/home
        links:
            - mariadb
            - mongodb
            - nginx-server
